name: Build and Test
description: Build the project and run tests
inputs: {}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build solution
      run: dotnet build --no-restore -c Release
      shell: bash

    - name: Run tests with coverage
      run: |
        dotnet tool install --global dotnet-coverage  
        dotnet-coverage collect "dotnet test --no-restore -c Release --logger trx --results-directory test-results" -f xml -o "coverage.xml"
      shell: bash
     
    - name: Upload test results
      if: (!cancelled())
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./test-results/**/*.trx

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: |
          test-results/**/*.xml
          test-results/**/*.trx
          test-results/**/*.json
