// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Entities;

#nullable disable

namespace Repository.Migrations;

[ExcludeFromCodeCoverage]
[DbContext(typeof(ValetingContext))]
[Migration("20250305163544_ReferenceData")]
partial class ReferenceData
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.2")
            .HasAnnotation("Proxies:ChangeTracking", false)
            .HasAnnotation("Proxies:CheckEquality", false)
            .HasAnnotation("Proxies:LazyLoading", true)
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Repository.Entities.ApplicationUser", b =>
            {
                b.Property<Guid>("Id")
                    .IsRequired()
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.Property<DateOnly>("DateOfBirth")
                    .IsRequired()
                    .HasColumnType("date");

                b.Property<int>("ContactNumber")
                    .HasColumnType("int");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("RoleId")
                    .IsRequired()
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Role_Id");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("LastLoginAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("ApplicationUser", (string)null);
            });

        modelBuilder.Entity("Repository.Entities.Booking", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id");

                b.Property<string>("Reference")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Customer_Id");

                b.Property<Guid>("FlexibilityId")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Flexibility_Id");

                b.Property<Guid>("VehicleSizeId")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("VehicleSize_Id");

                b.Property<DateTime>("ScheduledAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("StatusId")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Status_Id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("DecisionAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DecisionById")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("DecisionBy_Id");

                b.Property<bool>("RequiresApproval");

                b.Property<string>("Notes")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("FlexibilityId");

                b.HasIndex("VehicleSizeId");

                b.HasIndex("StatusId");

                b.HasIndex("DecisionById");

                b.ToTable("Booking", (string)null);
            });

        modelBuilder.Entity("Repository.Entities.RdFlexibility", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");
                
                b.Property<int>("NumberOfMinutes")
                    .IsRequired()
                    .HasColumnType("int");

                b.Property<bool>("Active")
                    .IsRequired()
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("RD_Flexibility", (string)null);
            });

        modelBuilder.Entity("Repository.Entities.RdVehicleSize", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("Active")
                    .IsRequired()
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("RD_VehicleSize", (string)null);
            });

        modelBuilder.Entity("Repository.Entities.RdRole", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("Active")
                    .IsRequired()
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("RD_Role", (string)null);
            });

        modelBuilder.Entity("Repository.Entities.RdStatus", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("Active")
                    .IsRequired()
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("RD_Status", (string)null);
            });

        modelBuilder.Entity("Repository.Entities.ApplicationUser", b =>
           {
               b.HasOne("Repository.Entities.RdRole", "Role")
                   .WithMany("ApplicationUsers")
                   .HasForeignKey("RoleId")
                   .IsRequired()
                   .HasConstraintName("FK_ApplicationUser_Role");

               b.Navigation("Role");
           });

        modelBuilder.Entity("Repository.Entities.Booking", b =>
            {
                b.HasOne("Repository.Entities.ApplicationUser", "Customer")
                    .WithMany("CustomerBookings")
                    .HasForeignKey("CustomerId")
                    .HasConstraintName("FK_Booking_ApplicationUser_Customer");

                b.HasOne("Repository.Entities.RdFlexibility", "Flexibility")
                    .WithMany("Bookings")
                    .HasForeignKey("FlexibilityId")
                    .IsRequired()
                    .HasConstraintName("FK_Booking_Flexibility");

                b.HasOne("Repository.Entities.RdVehicleSize", "VehicleSize")
                    .WithMany("Bookings")
                    .HasForeignKey("VehicleSizeId")
                    .IsRequired()
                    .HasConstraintName("FK_Booking_VehicleSize");

                b.HasOne("Repository.Entities.RdStatus", "Status")
                    .WithMany("Bookings")
                    .HasForeignKey("StatusId")
                    .IsRequired()
                    .HasConstraintName("FK_Booking_Status");

                b.HasOne("Repository.Entities.ApplicationUser", "DecisionBy")
                    .WithMany("DecisionBookings")
                    .HasForeignKey("DecisionById")
                    .HasConstraintName("FK_Booking_ApplicationUser_DecisionBy");

                b.Navigation("Customer");

                b.Navigation("Flexibility");

                b.Navigation("VehicleSize");

                b.Navigation("Status");

                b.Navigation("DecisionBy");
            });

        modelBuilder.Entity("Repository.Entities.RdFlexibility", b =>
            {
                b.Navigation("Bookings");
            });

        modelBuilder.Entity("Repository.Entities.RdVehicleSize", b =>
            {
                b.Navigation("Bookings");
            });

        modelBuilder.Entity("Repository.Entities.RdRole", b =>
            {
                b.Navigation("ApplicationUsers");
            });

        modelBuilder.Entity("Repository.Entities.RdStatus", b =>
            {
                b.Navigation("Bookings");
            });
#pragma warning restore 612, 618
    }
}
