// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Common.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Entities;

#nullable disable

namespace Repository.Migrations;

[ExcludeFromCodeCoverage]
[DbContext(typeof(ValetingContext))]
partial class ValetingContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.2")
            .HasAnnotation("Proxies:ChangeTracking", false)
            .HasAnnotation("Proxies:CheckEquality", false)
            .HasAnnotation("Proxies:LazyLoading", true)
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Repository.Entities.ApplicationUser", b =>
            {
                b.Property<Guid>("Id")
                    .IsRequired()
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ContactNumber")
                    .HasColumnType("int");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("RoleId")
                    .IsRequired()
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Role_Id");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("LastLoginAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("ApplicationUser", (string)null);
            });

        modelBuilder.Entity("Repository.Entities.Booking", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id");

                b.Property<bool?>("Approved")
                    .HasColumnType("bit");

                b.Property<DateTime>("BookingDate")
                    .HasColumnType("datetime");

                b.Property<Guid>("FlexibilityId")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Flexibility_Id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("VehicleSizeId")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("VehicleSize_Id");

                b.HasKey("Id");

                b.HasIndex("FlexibilityId");

                b.HasIndex("VehicleSizeId");

                b.ToTable("Booking", (string)null);
            });

        modelBuilder.Entity("Repository.Entities.RdFlexibility", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id");

                b.Property<bool>("Active")
                    .HasColumnType("bit");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("RD_Flexibility", (string)null);
            });

        modelBuilder.Entity("Repository.Entities.RdVehicleSize", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id");

                b.Property<bool>("Active")
                    .HasColumnType("bit");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("RD_VehicleSize", (string)null);
            });

        modelBuilder.Entity("Repository.Entities.RdRole", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id");

                var roleEnumConverter = new ValueConverter<RoleEnum, string>(
                    v => v.ToString(),
                    v => (RoleEnum)Enum.Parse(typeof(RoleEnum), v));

                b.Property<RoleEnum>("Name")
                    .HasConversion(roleEnumConverter)
                    .HasColumnType("int")
                    .HasColumnName("Name");

                b.HasKey("Id");

                b.ToTable("RD_Role", (string)null);
            });

        modelBuilder.Entity("Repository.Entities.Booking", b =>
            {
                b.HasOne("Repository.Entities.RdFlexibility", "Flexibility")
                    .WithMany("Bookings")
                    .HasForeignKey("FlexibilityId")
                    .IsRequired()
                    .HasConstraintName("FK_Booking_Flexibility");

                b.HasOne("Repository.Entities.RdVehicleSize", "VehicleSize")
                    .WithMany("Bookings")
                    .HasForeignKey("VehicleSizeId")
                    .IsRequired()
                    .HasConstraintName("FK_Booking_VehicleSize");

                b.Navigation("Flexibility");

                b.Navigation("VehicleSize");
            });

        modelBuilder.Entity("Repository.Entities.RdFlexibility", b =>
            {
                b.Navigation("Bookings");
            });

        modelBuilder.Entity("Repository.Entities.RdVehicleSize", b =>
            {
                b.Navigation("Bookings");
            });

        modelBuilder.Entity("Repository.Entities.ApplicationUser", b =>
            {
                b.HasOne("Repository.Entities.RdRole", "Role")
                    .WithMany("ApplicationUsers")
                    .HasForeignKey("RoleId")
                    .IsRequired()
                    .HasConstraintName("FK_ApplicationUser_Role");

                b.Navigation("Role");
            });

        modelBuilder.Entity("Repository.Entities.RdRole", b =>
            {
                b.Navigation("ApplicationUsers");
            });
#pragma warning restore 612, 618
    }
}
