//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valeting.Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Valeting.Common.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved cannot be empty..
        /// </summary>
        public static string ApprovedEmpty {
            get {
                return ResourceManager.GetString("ApprovedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookingDTO is not populated..
        /// </summary>
        public static string BookingDTONotPopulated {
            get {
                return ResourceManager.GetString("BookingDTONotPopulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking was not found..
        /// </summary>
        public static string BookingNotFound {
            get {
                return ResourceManager.GetString("BookingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date cannot be in the past..
        /// </summary>
        public static string DateInThePast {
            get {
                return ResourceManager.GetString("DateInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexibility cannot be empty..
        /// </summary>
        public static string FlexibilityEmpty {
            get {
                return ResourceManager.GetString("FlexibilityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexibility was not found..
        /// </summary>
        public static string FlexibilityNotFound {
            get {
                return ResourceManager.GetString("FlexibilityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexibility cannot be null..
        /// </summary>
        public static string FlexibilityNull {
            get {
                return ResourceManager.GetString("FlexibilityNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a valid contact number for the booking..
        /// </summary>
        public static string InvalidBookingContactNumber {
            get {
                return ResourceManager.GetString("InvalidBookingContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a valid date for the booking..
        /// </summary>
        public static string InvalidBookingDate {
            get {
                return ResourceManager.GetString("InvalidBookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a valid email for the booking..
        /// </summary>
        public static string InvalidBookingEmail {
            get {
                return ResourceManager.GetString("InvalidBookingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a valid id for the booking..
        /// </summary>
        public static string InvalidBookingId {
            get {
                return ResourceManager.GetString("InvalidBookingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a valid name for the booking..
        /// </summary>
        public static string InvalidBookingName {
            get {
                return ResourceManager.GetString("InvalidBookingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a valid id for the flexibility..
        /// </summary>
        public static string InvalidFlexibilityId {
            get {
                return ResourceManager.GetString("InvalidFlexibilityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page number is invalid..
        /// </summary>
        public static string InvalidPageNumber {
            get {
                return ResourceManager.GetString("InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a valid password..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a valid username..
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a valid id for the vehicle size..
        /// </summary>
        public static string InvalidVehicleSizeId {
            get {
                return ResourceManager.GetString("InvalidVehicleSizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not initialized..
        /// </summary>
        public static string NotInitializeRepository {
            get {
                return ResourceManager.GetString("NotInitializeRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDTO is not populated..
        /// </summary>
        public static string UserDTONotPopulated {
            get {
                return ResourceManager.GetString("UserDTONotPopulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Size cannot be empty..
        /// </summary>
        public static string VehicleSizeEmpty {
            get {
                return ResourceManager.GetString("VehicleSizeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Size was not found..
        /// </summary>
        public static string VehicleSizeNotFound {
            get {
                return ResourceManager.GetString("VehicleSizeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Size cannot be null..
        /// </summary>
        public static string VehicleSizeNull {
            get {
                return ResourceManager.GetString("VehicleSizeNull", resourceCulture);
            }
        }
    }
}
