name: Swagger Gen and Update
description: Generate Swagger file and create PR
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  swagger-path:
    description: 'Path to Swagger JSON output'
    required: true
  target-dll-path:
    description: 'Path to dll to generate the swagger'
    required: true
  swagger-version:
    description: 'Swagger docs version'
    required: true
  target-branch:
    description: 'Branch to push Swagger update'
    default: 'swagger-update'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies (global)
      shell: bash
      run: dotnet tool install --global Swashbuckle.AspNetCore.Cli

    - name: Add .NET tools to PATH
      shell: bash
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Restore dependencies
      shell: bash
      run: dotnet restore

    - name: Build solution
      shell: bash
      run: dotnet build --no-restore -c Release

    - name: Generate Swagger JSON
      shell: bash
      run: |
        set -euo pipefail
        swagger tofile --output "${{ inputs.swagger-path }}" ${{ inputs.target-dll-path }} ${{ inputs.swagger-version }}

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    - name: Create or switch to branch
      shell: bash
      run: |
        if git show-ref --quiet refs/heads/${{ inputs.target-branch }}; then
          git checkout ${{ inputs.target-branch }}
        else
          git checkout -b ${{ inputs.target-branch }}
        fi

    - name: Commit Swagger file if changed
      shell: bash
      run: |
        git add ${{ inputs.swagger-path }}
        if git diff --cached --quiet; then
          echo "No changes in Swagger file — skipping commit."
          exit 0
        fi
        git commit -m "Update Swagger file [skip ci]"

    - name: Push branch
      shell: bash
      run: git push origin ${{ inputs.target-branch }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ inputs.github-token }}
        title: "Update Swagger file"
        body: "Automatic Swagger file update"
        base: main
        branch: ${{ inputs.target-branch }}
        delete-branch: true
