name: Docker Publish on Tag

run-name: Docker publish ${{ github.ref_name }}

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write


jobs:
  docker-publish:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/valeting-api:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
